GET http://localhost:8082
###
GET http://localhost:8082/currencies
###
GET http://localhost:8082/currencies/usdd
###
GET http://localhost:8082/posts/1234/comments/false
###
GET http://localhost:8082/currencies?min_value=0.001
###
GET http://localhost:8082/users
Authorization: LetMeIn
###
GET http://localhost:8082/users/0e7fef61-213b-4e20-b6cf-b4d05a7ac79c
###
GET http://localhost:8082/users/search?gender=male&age=49
Authorization: LetMeIn
###
GET http://localhost:8082/users/search?gender=50
###
GET http://localhost:8082/users/search?age=MALE
###
GET http://localhost:8082/users/search
###
POST http://localhost:8082/XYZ